
package com.ticketnetwork.tnwebservices_test.tnwebservice.v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TNWebServiceStringInputsHttpGet", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TNWebServiceStringInputsHttpGet {


    /**
     * 
     * @param performerName
     * @param whereClause
     * @param eventDate
     * @param grandchildCategoryID
     * @param onlyMine
     * @param endDate
     * @param beginDate
     * @param performerID
     * @param stateID
     * @param nearZip
     * @param websiteConfigID
     * @param venueName
     * @param numberOfEvents
     * @param noPerformers
     * @param orderByClause
     * @param parentCategoryID
     * @param childCategoryID
     * @param lowPrice
     * @param stateProvDesc
     * @param eventID
     * @param eventName
     * @param modificationDate
     * @param highPrice
     * @param cityZip
     * @param venueID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfEvent
     */
    @WebMethod(operationName = "GetEvents")
    @WebResult(name = "ArrayOfEvent", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfEvent getEvents(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "numberOfEvents")
        String numberOfEvents,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "eventID")
        String eventID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "eventName")
        String eventName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "eventDate")
        String eventDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "beginDate")
        String beginDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endDate")
        String endDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "venueID")
        String venueID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "venueName")
        String venueName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "stateProvDesc")
        String stateProvDesc,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "stateID")
        String stateID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "cityZip")
        String cityZip,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "nearZip")
        String nearZip,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentCategoryID")
        String parentCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "childCategoryID")
        String childCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "grandchildCategoryID")
        String grandchildCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "performerID")
        String performerID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "performerName")
        String performerName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "noPerformers")
        String noPerformers,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "lowPrice")
        String lowPrice,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "highPrice")
        String highPrice,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "modificationDate")
        String modificationDate,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "onlyMine")
        String onlyMine,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "whereClause")
        String whereClause,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "orderByClause")
        String orderByClause);

    /**
     * 
     * @param whereClause
     * @param eventID
     * @param numberOfRecords
     * @param requestedTixSplit
     * @param orderByClause
     * @param websiteConfigID
     * @param highPrice
     * @param lowPrice
     * @param ticketGroupID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfTicketGroup
     */
    @WebMethod(operationName = "GetTickets")
    @WebResult(name = "ArrayOfTicketGroup", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfTicketGroup getTickets(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "numberOfRecords")
        String numberOfRecords,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "eventID")
        String eventID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "lowPrice")
        String lowPrice,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "highPrice")
        String highPrice,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ticketGroupID")
        String ticketGroupID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "requestedTixSplit")
        String requestedTixSplit,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "whereClause")
        String whereClause,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "orderByClause")
        String orderByClause);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfCategory
     */
    @WebMethod(operationName = "GetCategories")
    @WebResult(name = "ArrayOfCategory", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfCategory getCategories(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfCategory
     */
    @WebMethod(operationName = "GetCategoriesMasterList")
    @WebResult(name = "ArrayOfCategory", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfCategory getCategoriesMasterList(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfCountry
     */
    @WebMethod(operationName = "GetCountries")
    @WebResult(name = "ArrayOfCountry", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfCountry getCountries(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param countryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.Country
     */
    @WebMethod(operationName = "GetCountryByID")
    @WebResult(name = "Country", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public Country getCountryByID(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "countryID")
        String countryID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfEventPerformer
     */
    @WebMethod(operationName = "GetEventPerformers")
    @WebResult(name = "ArrayOfEventPerformer", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfEventPerformer getEventPerformers(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID);

    /**
     * 
     * @param grandchildCategoryID
     * @param hasEvent
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfPerformer
     */
    @WebMethod(operationName = "GetPerformerByCategory")
    @WebResult(name = "ArrayOfPerformer", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfPerformer getPerformerByCategory(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentCategoryID")
        String parentCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "childCategoryID")
        String childCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "grandchildCategoryID")
        String grandchildCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "hasEvent")
        String hasEvent);

    /**
     * 
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfCategory
     */
    @WebMethod(operationName = "GetSublevelCategories")
    @WebResult(name = "ArrayOfCategory", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfCategory getSublevelCategories(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentCategoryID")
        String parentCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "childCategoryID")
        String childCategoryID);

    /**
     * 
     * @param websiteConfigID
     * @param venueID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfVenue
     */
    @WebMethod(operationName = "GetVenue")
    @WebResult(name = "ArrayOfVenue", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfVenue getVenue(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "venueID")
        String venueID);

    /**
     * 
     * @param websiteConfigID
     * @param venueID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfVenueConfiguration
     */
    @WebMethod(operationName = "GetVenueConfigurations")
    @WebResult(name = "ArrayOfVenueConfiguration", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfVenueConfiguration getVenueConfigurations(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "venueID")
        String venueID);

    /**
     * 
     * @param grandchildCategoryID
     * @param numReturned
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfPerformerPercent
     */
    @WebMethod(operationName = "GetHighInventoryPerformers")
    @WebResult(name = "ArrayOfPerformerPercent", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfPerformerPercent getHighInventoryPerformers(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "numReturned")
        String numReturned,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentCategoryID")
        String parentCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "childCategoryID")
        String childCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "grandchildCategoryID")
        String grandchildCategoryID);

    /**
     * 
     * @param grandchildCategoryID
     * @param numReturned
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfPerformerPercent
     */
    @WebMethod(operationName = "GetHighSalesPerformers")
    @WebResult(name = "ArrayOfPerformerPercent", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfPerformerPercent getHighSalesPerformers(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "numReturned")
        String numReturned,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "parentCategoryID")
        String parentCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "childCategoryID")
        String childCategoryID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "grandchildCategoryID")
        String grandchildCategoryID);

    /**
     * 
     * @param whereClause
     * @param searchTerms
     * @param orderByClause
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfEvent
     */
    @WebMethod(operationName = "SearchEvents")
    @WebResult(name = "ArrayOfEvent", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfEvent searchEvents(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "searchTerms")
        String searchTerms,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "whereClause")
        String whereClause,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "orderByClause")
        String orderByClause);

    /**
     * 
     * @param countryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.ArrayOfStates
     */
    @WebMethod(operationName = "GetStates")
    @WebResult(name = "ArrayOfStates", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public ArrayOfStates getStates(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "countryID")
        String countryID);

    /**
     * 
     * @param eventID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices_test.tnwebservice.v3.PricingInformation
     */
    @WebMethod(operationName = "GetPricingInfo")
    @WebResult(name = "PricingInformation", targetNamespace = "http://tnwebservices-test.ticketnetwork.com/tnwebservice/v3.0", partName = "Body")
    public PricingInformation getPricingInfo(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "websiteConfigID")
        String websiteConfigID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "eventID")
        String eventID);

}
