
package com.ticketnetwork.tnwebservices.tnwebservice.v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TNWebServiceStringInputsSoap", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TNWebServiceStringInputsSoap {


    /**
     * 
     * @param performerName
     * @param whereClause
     * @param eventDate
     * @param grandchildCategoryID
     * @param onlyMine
     * @param endDate
     * @param beginDate
     * @param performerID
     * @param stateID
     * @param nearZip
     * @param websiteConfigID
     * @param venueName
     * @param numberOfEvents
     * @param noPerformers
     * @param orderByClause
     * @param parentCategoryID
     * @param childCategoryID
     * @param lowPrice
     * @param stateProvDesc
     * @param eventID
     * @param eventName
     * @param modificationDate
     * @param highPrice
     * @param cityZip
     * @param venueID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfEvent
     */
    @WebMethod(operationName = "GetEvents", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetEvents")
    @WebResult(name = "GetEventsResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetEvents", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetEvents")
    @ResponseWrapper(localName = "GetEventsResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetEventsResponse")
    public ArrayOfEvent getEvents(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "numberOfEvents", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String numberOfEvents,
        @WebParam(name = "eventID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String eventID,
        @WebParam(name = "eventName", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String eventName,
        @WebParam(name = "eventDate", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String eventDate,
        @WebParam(name = "beginDate", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String beginDate,
        @WebParam(name = "endDate", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String endDate,
        @WebParam(name = "venueID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String venueID,
        @WebParam(name = "venueName", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String venueName,
        @WebParam(name = "stateProvDesc", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String stateProvDesc,
        @WebParam(name = "stateID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String stateID,
        @WebParam(name = "cityZip", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String cityZip,
        @WebParam(name = "nearZip", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String nearZip,
        @WebParam(name = "parentCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String parentCategoryID,
        @WebParam(name = "childCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String childCategoryID,
        @WebParam(name = "grandchildCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String grandchildCategoryID,
        @WebParam(name = "performerID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String performerID,
        @WebParam(name = "performerName", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String performerName,
        @WebParam(name = "noPerformers", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String noPerformers,
        @WebParam(name = "lowPrice", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String lowPrice,
        @WebParam(name = "highPrice", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String highPrice,
        @WebParam(name = "modificationDate", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String modificationDate,
        @WebParam(name = "onlyMine", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String onlyMine,
        @WebParam(name = "whereClause", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String whereClause,
        @WebParam(name = "orderByClause", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String orderByClause);

    /**
     * 
     * @param whereClause
     * @param eventID
     * @param numberOfRecords
     * @param requestedTixSplit
     * @param orderByClause
     * @param websiteConfigID
     * @param highPrice
     * @param lowPrice
     * @param ticketGroupID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfTicketGroup
     */
    @WebMethod(operationName = "GetTickets", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetTickets")
    @WebResult(name = "GetTicketsResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetTickets", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetTickets")
    @ResponseWrapper(localName = "GetTicketsResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetTicketsResponse")
    public ArrayOfTicketGroup getTickets(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "numberOfRecords", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String numberOfRecords,
        @WebParam(name = "eventID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String eventID,
        @WebParam(name = "lowPrice", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String lowPrice,
        @WebParam(name = "highPrice", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String highPrice,
        @WebParam(name = "ticketGroupID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String ticketGroupID,
        @WebParam(name = "requestedTixSplit", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String requestedTixSplit,
        @WebParam(name = "whereClause", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String whereClause,
        @WebParam(name = "orderByClause", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String orderByClause);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfCategory
     */
    @WebMethod(operationName = "GetCategories", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetCategories")
    @WebResult(name = "GetCategoriesResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetCategories", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetCategories")
    @ResponseWrapper(localName = "GetCategoriesResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetCategoriesResponse")
    public ArrayOfCategory getCategories(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfCategory
     */
    @WebMethod(operationName = "GetCategoriesMasterList", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetCategoriesMasterList")
    @WebResult(name = "GetCategoriesMasterListResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetCategoriesMasterList", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetCategoriesMasterList")
    @ResponseWrapper(localName = "GetCategoriesMasterListResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetCategoriesMasterListResponse")
    public ArrayOfCategory getCategoriesMasterList(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfCountry
     */
    @WebMethod(operationName = "GetCountries", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetCountries")
    @WebResult(name = "GetCountriesResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetCountries", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetCountries")
    @ResponseWrapper(localName = "GetCountriesResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetCountriesResponse")
    public ArrayOfCountry getCountries(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID);

    /**
     * 
     * @param countryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.Country
     */
    @WebMethod(operationName = "GetCountryByID", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetCountryByID")
    @WebResult(name = "GetCountryByIDResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetCountryByID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetCountryByID")
    @ResponseWrapper(localName = "GetCountryByIDResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetCountryByIDResponse")
    public Country getCountryByID(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "countryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String countryID);

    /**
     * 
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfEventPerformer
     */
    @WebMethod(operationName = "GetEventPerformers", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetEventPerformers")
    @WebResult(name = "GetEventPerformersResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetEventPerformers", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetEventPerformers")
    @ResponseWrapper(localName = "GetEventPerformersResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetEventPerformersResponse")
    public ArrayOfEventPerformer getEventPerformers(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID);

    /**
     * 
     * @param grandchildCategoryID
     * @param hasEvent
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfPerformer
     */
    @WebMethod(operationName = "GetPerformerByCategory", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetPerformerByCategory")
    @WebResult(name = "GetPerformerByCategoryResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetPerformerByCategory", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetPerformerByCategory")
    @ResponseWrapper(localName = "GetPerformerByCategoryResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetPerformerByCategoryResponse")
    public ArrayOfPerformer getPerformerByCategory(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "parentCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String parentCategoryID,
        @WebParam(name = "childCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String childCategoryID,
        @WebParam(name = "grandchildCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String grandchildCategoryID,
        @WebParam(name = "hasEvent", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String hasEvent);

    /**
     * 
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfCategory
     */
    @WebMethod(operationName = "GetSublevelCategories", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetSublevelCategories")
    @WebResult(name = "GetSublevelCategoriesResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetSublevelCategories", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetSublevelCategories")
    @ResponseWrapper(localName = "GetSublevelCategoriesResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetSublevelCategoriesResponse")
    public ArrayOfCategory getSublevelCategories(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "parentCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String parentCategoryID,
        @WebParam(name = "childCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String childCategoryID);

    /**
     * 
     * @param websiteConfigID
     * @param venueID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfVenue
     */
    @WebMethod(operationName = "GetVenue", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetVenue")
    @WebResult(name = "GetVenueResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetVenue", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetVenue")
    @ResponseWrapper(localName = "GetVenueResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetVenueResponse")
    public ArrayOfVenue getVenue(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "venueID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String venueID);

    /**
     * 
     * @param websiteConfigID
     * @param venueID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfVenueConfiguration
     */
    @WebMethod(operationName = "GetVenueConfigurations", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetVenueConfigurations")
    @WebResult(name = "GetVenueConfigurationsResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetVenueConfigurations", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetVenueConfigurations")
    @ResponseWrapper(localName = "GetVenueConfigurationsResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetVenueConfigurationsResponse")
    public ArrayOfVenueConfiguration getVenueConfigurations(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "venueID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String venueID);

    /**
     * 
     * @param grandchildCategoryID
     * @param numReturned
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfPerformerPercent
     */
    @WebMethod(operationName = "GetHighInventoryPerformers", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetHighInventoryPerformers")
    @WebResult(name = "GetHighInventoryPerformersResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetHighInventoryPerformers", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetHighInventoryPerformers")
    @ResponseWrapper(localName = "GetHighInventoryPerformersResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetHighInventoryPerformersResponse")
    public ArrayOfPerformerPercent getHighInventoryPerformers(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "numReturned", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String numReturned,
        @WebParam(name = "parentCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String parentCategoryID,
        @WebParam(name = "childCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String childCategoryID,
        @WebParam(name = "grandchildCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String grandchildCategoryID);

    /**
     * 
     * @param grandchildCategoryID
     * @param numReturned
     * @param parentCategoryID
     * @param childCategoryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfPerformerPercent
     */
    @WebMethod(operationName = "GetHighSalesPerformers", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetHighSalesPerformers")
    @WebResult(name = "GetHighSalesPerformersResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetHighSalesPerformers", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetHighSalesPerformers")
    @ResponseWrapper(localName = "GetHighSalesPerformersResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetHighSalesPerformersResponse")
    public ArrayOfPerformerPercent getHighSalesPerformers(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "numReturned", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String numReturned,
        @WebParam(name = "parentCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String parentCategoryID,
        @WebParam(name = "childCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String childCategoryID,
        @WebParam(name = "grandchildCategoryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String grandchildCategoryID);

    /**
     * 
     * @param whereClause
     * @param searchTerms
     * @param orderByClause
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfEvent
     */
    @WebMethod(operationName = "SearchEvents", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/SearchEvents")
    @WebResult(name = "SearchEventsResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "SearchEvents", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.SearchEvents")
    @ResponseWrapper(localName = "SearchEventsResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.SearchEventsResponse")
    public ArrayOfEvent searchEvents(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "searchTerms", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String searchTerms,
        @WebParam(name = "whereClause", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String whereClause,
        @WebParam(name = "orderByClause", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String orderByClause);

    /**
     * 
     * @param countryID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.ArrayOfStates
     */
    @WebMethod(operationName = "GetStates", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetStates")
    @WebResult(name = "GetStatesResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetStates", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetStates")
    @ResponseWrapper(localName = "GetStatesResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetStatesResponse")
    public ArrayOfStates getStates(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "countryID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String countryID);

    /**
     * 
     * @param eventID
     * @param websiteConfigID
     * @return
     *     returns com.ticketnetwork.tnwebservices.tnwebservice.v3.PricingInformation
     */
    @WebMethod(operationName = "GetPricingInfo", action = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0/GetPricingInfo")
    @WebResult(name = "GetPricingInfoResult", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
    @RequestWrapper(localName = "GetPricingInfo", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetPricingInfo")
    @ResponseWrapper(localName = "GetPricingInfoResponse", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0", className = "com.ticketnetwork.tnwebservices.tnwebservice.v3.GetPricingInfoResponse")
    public PricingInformation getPricingInfo(
        @WebParam(name = "websiteConfigID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String websiteConfigID,
        @WebParam(name = "eventID", targetNamespace = "http://tnwebservices.ticketnetwork.com/tnwebservice/v3.0")
        String eventID);

}
